import type { DaFinkConfig } from './config.js';

type StyleName = 'minimal' | 'neumorph' | 'brutalist';
type PaletteName = 'zinc' | 'ocean' | 'ember' | 'forest' | 'noir' | 'plum';

interface TokenBlock
{
	light: Record<string, string>;
	dark: Record<string, string>;
}

const STYLE_TOKENS: Record<StyleName, TokenBlock> = {
	minimal: {
		light: {
			'--radius-sm': '0.375rem',
			'--radius': '0.5rem',
			'--radius-lg': '0.75rem',
			'--border-width': '1px',
			'--shadow-sm': '0 1px 2px 0 rgb(0 0 0 / 0.05)',
			'--shadow': '0 1px 3px 0 rgb(0 0 0 / 0.10), 0 1px 2px -1px rgb(0 0 0 / 0.10)',
			'--shadow-lg': '0 10px 15px -3px rgb(0 0 0 / 0.10), 0 4px 6px -4px rgb(0 0 0 / 0.10)',
			'--backdrop-blur': '0px',
			'--surface-alpha': '1',
			'--inner-shadow': 'none',
			'--input-focus-shadow': '0 0 0 2px var(--color-input-ring)',
		},
		dark: {},
	},
	neumorph: {
		light: {
			'--radius-sm': '0.875rem',
			'--radius': '1.25rem',
			'--radius-lg': '1.5rem',
			'--border-width': '0px',
			'--shadow-sm': '5px 5px 12px rgb(0 0 0 / 0.14), -5px -5px 12px rgb(255 255 255 / 0.80)',
			'--shadow': '8px 8px 18px rgb(0 0 0 / 0.18), -8px -8px 18px rgb(255 255 255 / 0.85)',
			'--shadow-lg': '12px 12px 24px rgb(0 0 0 / 0.20), -12px -12px 24px rgb(255 255 255 / 0.88)',
			'--backdrop-blur': '0px',
			'--surface-alpha': '1',
			'--inner-shadow': 'inset 5px 5px 12px rgb(0 0 0 / 0.14), inset -5px -5px 12px rgb(255 255 255 / 0.80)',
			'--input-focus-shadow': '0 0 0 2px var(--color-input-ring), inset 5px 5px 12px rgb(0 0 0 / 0.14), inset -5px -5px 12px rgb(255 255 255 / 0.80)',
		},
		dark: {
			'--radius-sm': '0.875rem',
			'--radius': '1.25rem',
			'--radius-lg': '1.5rem',
			'--border-width': '0px',
			'--shadow-sm': '5px 5px 12px rgb(0 0 0 / 0.55), -5px -5px 12px rgb(255 255 255 / 0.06)',
			'--shadow': '8px 8px 18px rgb(0 0 0 / 0.60), -8px -8px 18px rgb(255 255 255 / 0.07)',
			'--shadow-lg': '12px 12px 24px rgb(0 0 0 / 0.65), -12px -12px 24px rgb(255 255 255 / 0.08)',
			'--backdrop-blur': '0px',
			'--surface-alpha': '1',
			'--inner-shadow': 'inset 5px 5px 12px rgb(0 0 0 / 0.55), inset -5px -5px 12px rgb(255 255 255 / 0.06)',
			'--input-focus-shadow': '0 0 0 2px var(--color-input-ring), inset 5px 5px 12px rgb(0 0 0 / 0.55), inset -5px -5px 12px rgb(255 255 255 / 0.06)',
		},
	},
	brutalist: {
		light: {
			'--radius-sm': '0px',
			'--radius': '0px',
			'--radius-lg': '0px',
			'--border-width': '2px',
			'--shadow-sm': '5px 5px 0 0 var(--shadow-color)',
			'--shadow': '7px 7px 0 0 var(--shadow-color)',
			'--shadow-lg': '9px 9px 0 0 var(--shadow-color)',
			'--backdrop-blur': '0px',
			'--surface-alpha': '1',
			'--inner-shadow': 'none',
			'--input-focus-shadow': '0 0 0 2px var(--color-input-ring)',
		},
		dark: {
			'--shadow-color': '#3c3c46',
		},
	},
};

const PALETTE_TOKENS: Record<PaletteName, TokenBlock> = {
	zinc: {
		light: {
			'--color-brand': '#18181b',
			'--color-brand-hover': '#27272a',
			'--color-brand-active': '#3f3f46',
			'--color-brand-ring': '#18181b',
			'--color-brand-fg': '#ffffff',
			'--color-danger': '#dc2626',
			'--color-danger-hover': '#b91c1c',
			'--color-danger-active': '#991b1b',
			'--color-danger-ring': '#dc2626',
			'--color-success': '#16a34a',
			'--color-success-bg': '#f0fdf4',
			'--color-success-border': '#bbf7d0',
			'--color-warning': '#d97706',
			'--color-warning-bg': '#fffbeb',
			'--color-warning-border': '#fde68a',
			'--color-surface': '#ffffff',
			'--color-surface-hover': '#f9fafb',
			'--color-surface-active': '#f4f4f5',
			'--color-surface-border': '#e4e4e7',
			'--color-surface-border-hover': '#d4d4d8',
			'--color-text': '#18181b',
			'--color-text-muted': '#52525b',
			'--color-text-subtle': '#a1a1aa',
			'--color-text-inverted': '#ffffff',
			'--color-input-border': '#d4d4d8',
			'--color-input-border-hover': '#a1a1aa',
			'--color-input-ring': '#18181b',
			'--color-input-placeholder': '#a1a1aa',
			'--color-input-disabled-bg': '#f4f4f5',
			'--color-input-disabled-text': '#a1a1aa',
			'--color-input-error': '#dc2626',
			'--color-input-error-ring': '#dc2626',
		},
		dark: {
			'--color-brand': '#e8e8ea',
			'--color-brand-hover': '#d0d0d4',
			'--color-brand-active': '#b4b4b9',
			'--color-brand-ring': '#e8e8ea',
			'--color-brand-fg': '#111113',
			'--color-danger': '#f87171',
			'--color-danger-hover': '#fca5a5',
			'--color-danger-active': '#fecaca',
			'--color-danger-ring': '#f87171',
			'--color-success': '#4ade80',
			'--color-success-bg': '#052e16',
			'--color-success-border': '#166534',
			'--color-warning': '#fbbf24',
			'--color-warning-bg': '#1c1200',
			'--color-warning-border': '#92400e',
			'--color-surface': '#111113',
			'--color-surface-hover': '#1c1c1f',
			'--color-surface-active': '#26262a',
			'--color-surface-border': '#2e2e32',
			'--color-surface-border-hover': '#3e3e43',
			'--color-text': '#e8e8ea',
			'--color-text-muted': '#8e8e9a',
			'--color-text-subtle': '#54545e',
			'--color-text-inverted': '#111113',
			'--color-input-border': '#2e2e32',
			'--color-input-border-hover': '#3e3e43',
			'--color-input-ring': '#e8e8ea',
			'--color-input-placeholder': '#54545e',
			'--color-input-disabled-bg': '#1c1c1f',
			'--color-input-disabled-text': '#2e2e32',
			'--color-input-error': '#f87171',
			'--color-input-error-ring': '#f87171',
		},
	},
	ocean: {
		light: {
			'--color-brand': '#0284c7',
			'--color-brand-hover': '#0369a1',
			'--color-brand-active': '#075985',
			'--color-brand-ring': '#0284c7',
			'--color-brand-fg': '#ffffff',
			'--color-danger': '#dc2626',
			'--color-danger-hover': '#b91c1c',
			'--color-danger-active': '#991b1b',
			'--color-danger-ring': '#dc2626',
			'--color-success': '#16a34a',
			'--color-success-bg': '#f0fdf4',
			'--color-success-border': '#bbf7d0',
			'--color-warning': '#d97706',
			'--color-warning-bg': '#fffbeb',
			'--color-warning-border': '#fde68a',
			'--color-surface': '#ffffff',
			'--color-surface-hover': '#f0f9ff',
			'--color-surface-active': '#e0f2fe',
			'--color-surface-border': '#bae6fd',
			'--color-surface-border-hover': '#7dd3fc',
			'--color-text': '#0c4a6e',
			'--color-text-muted': '#0369a1',
			'--color-text-subtle': '#93c5fd',
			'--color-text-inverted': '#ffffff',
			'--color-input-border': '#bae6fd',
			'--color-input-border-hover': '#7dd3fc',
			'--color-input-ring': '#0284c7',
			'--color-input-placeholder': '#93c5fd',
			'--color-input-disabled-bg': '#e0f2fe',
			'--color-input-disabled-text': '#93c5fd',
			'--color-input-error': '#dc2626',
			'--color-input-error-ring': '#dc2626',
		},
		dark: {
			'--color-brand': '#38bdf8',
			'--color-brand-hover': '#7dd3fc',
			'--color-brand-active': '#bae6fd',
			'--color-brand-ring': '#38bdf8',
			'--color-brand-fg': '#0c4a6e',
			'--color-danger': '#f87171',
			'--color-danger-hover': '#fca5a5',
			'--color-danger-active': '#fecaca',
			'--color-danger-ring': '#f87171',
			'--color-success': '#4ade80',
			'--color-success-bg': '#052e16',
			'--color-success-border': '#166534',
			'--color-warning': '#fbbf24',
			'--color-warning-bg': '#1c1200',
			'--color-warning-border': '#92400e',
			'--color-surface': '#040d14',
			'--color-surface-hover': '#071628',
			'--color-surface-active': '#0c2040',
			'--color-surface-border': '#102a4c',
			'--color-surface-border-hover': '#1a3f6f',
			'--color-text': '#e0f2fe',
			'--color-text-muted': '#7dd3fc',
			'--color-text-subtle': '#102a4c',
			'--color-text-inverted': '#040d14',
			'--color-input-border': '#102a4c',
			'--color-input-border-hover': '#1a3f6f',
			'--color-input-ring': '#38bdf8',
			'--color-input-placeholder': '#102a4c',
			'--color-input-disabled-bg': '#071628',
			'--color-input-disabled-text': '#102a4c',
			'--color-input-error': '#f87171',
			'--color-input-error-ring': '#f87171',
		},
	},
	ember: {
		light: {
			'--color-brand': '#ea580c',
			'--color-brand-hover': '#c2410c',
			'--color-brand-active': '#9a3412',
			'--color-brand-ring': '#ea580c',
			'--color-brand-fg': '#ffffff',
			'--color-danger': '#dc2626',
			'--color-danger-hover': '#b91c1c',
			'--color-danger-active': '#991b1b',
			'--color-danger-ring': '#dc2626',
			'--color-success': '#16a34a',
			'--color-success-bg': '#f0fdf4',
			'--color-success-border': '#bbf7d0',
			'--color-warning': '#ca8a04',
			'--color-warning-bg': '#fefce8',
			'--color-warning-border': '#fef08a',
			'--color-surface': '#ffffff',
			'--color-surface-hover': '#fff7ed',
			'--color-surface-active': '#ffedd5',
			'--color-surface-border': '#fed7aa',
			'--color-surface-border-hover': '#fdba74',
			'--color-text': '#431407',
			'--color-text-muted': '#9a3412',
			'--color-text-subtle': '#fdba74',
			'--color-text-inverted': '#ffffff',
			'--color-input-border': '#fed7aa',
			'--color-input-border-hover': '#fdba74',
			'--color-input-ring': '#ea580c',
			'--color-input-placeholder': '#fdba74',
			'--color-input-disabled-bg': '#ffedd5',
			'--color-input-disabled-text': '#fdba74',
			'--color-input-error': '#dc2626',
			'--color-input-error-ring': '#dc2626',
		},
		dark: {
			'--color-brand': '#fb923c',
			'--color-brand-hover': '#fdba74',
			'--color-brand-active': '#fed7aa',
			'--color-brand-ring': '#fb923c',
			'--color-brand-fg': '#431407',
			'--color-danger': '#f87171',
			'--color-danger-hover': '#fca5a5',
			'--color-danger-active': '#fecaca',
			'--color-danger-ring': '#f87171',
			'--color-success': '#4ade80',
			'--color-success-bg': '#052e16',
			'--color-success-border': '#166534',
			'--color-warning': '#fde047',
			'--color-warning-bg': '#1c1000',
			'--color-warning-border': '#713f12',
			'--color-surface': '#150800',
			'--color-surface-hover': '#220d00',
			'--color-surface-active': '#2f1400',
			'--color-surface-border': '#3d1d00',
			'--color-surface-border-hover': '#522900',
			'--color-text': '#ffedd5',
			'--color-text-muted': '#fb923c',
			'--color-text-subtle': '#3d1d00',
			'--color-text-inverted': '#150800',
			'--color-input-border': '#3d1d00',
			'--color-input-border-hover': '#522900',
			'--color-input-ring': '#fb923c',
			'--color-input-placeholder': '#3d1d00',
			'--color-input-disabled-bg': '#220d00',
			'--color-input-disabled-text': '#3d1d00',
			'--color-input-error': '#f87171',
			'--color-input-error-ring': '#f87171',
		},
	},
	forest: {
		light: {
			'--color-brand': '#16a34a',
			'--color-brand-hover': '#15803d',
			'--color-brand-active': '#166534',
			'--color-brand-ring': '#16a34a',
			'--color-brand-fg': '#ffffff',
			'--color-danger': '#dc2626',
			'--color-danger-hover': '#b91c1c',
			'--color-danger-active': '#991b1b',
			'--color-danger-ring': '#dc2626',
			'--color-success': '#16a34a',
			'--color-success-bg': '#f0fdf4',
			'--color-success-border': '#bbf7d0',
			'--color-warning': '#d97706',
			'--color-warning-bg': '#fffbeb',
			'--color-warning-border': '#fde68a',
			'--color-surface': '#ffffff',
			'--color-surface-hover': '#f0fdf4',
			'--color-surface-active': '#dcfce7',
			'--color-surface-border': '#bbf7d0',
			'--color-surface-border-hover': '#86efac',
			'--color-text': '#14532d',
			'--color-text-muted': '#166534',
			'--color-text-subtle': '#86efac',
			'--color-text-inverted': '#ffffff',
			'--color-input-border': '#bbf7d0',
			'--color-input-border-hover': '#86efac',
			'--color-input-ring': '#16a34a',
			'--color-input-placeholder': '#86efac',
			'--color-input-disabled-bg': '#dcfce7',
			'--color-input-disabled-text': '#86efac',
			'--color-input-error': '#dc2626',
			'--color-input-error-ring': '#dc2626',
		},
		dark: {
			'--color-brand': '#4ade80',
			'--color-brand-hover': '#86efac',
			'--color-brand-active': '#bbf7d0',
			'--color-brand-ring': '#4ade80',
			'--color-brand-fg': '#14532d',
			'--color-danger': '#f87171',
			'--color-danger-hover': '#fca5a5',
			'--color-danger-active': '#fecaca',
			'--color-danger-ring': '#f87171',
			'--color-success': '#4ade80',
			'--color-success-bg': '#052e16',
			'--color-success-border': '#166534',
			'--color-warning': '#fbbf24',
			'--color-warning-bg': '#1c1200',
			'--color-warning-border': '#92400e',
			'--color-surface': '#020d06',
			'--color-surface-hover': '#041508',
			'--color-surface-active': '#071d0c',
			'--color-surface-border': '#0c2c14',
			'--color-surface-border-hover': '#13431e',
			'--color-text': '#dcfce7',
			'--color-text-muted': '#4ade80',
			'--color-text-subtle': '#0c2c14',
			'--color-text-inverted': '#020d06',
			'--color-input-border': '#0c2c14',
			'--color-input-border-hover': '#13431e',
			'--color-input-ring': '#4ade80',
			'--color-input-placeholder': '#0c2c14',
			'--color-input-disabled-bg': '#041508',
			'--color-input-disabled-text': '#0c2c14',
			'--color-input-error': '#f87171',
			'--color-input-error-ring': '#f87171',
		},
	},
	noir: {
		light: {
			'--color-brand': '#1e293b',
			'--color-brand-hover': '#334155',
			'--color-brand-active': '#475569',
			'--color-brand-ring': '#1e293b',
			'--color-brand-fg': '#ffffff',
			'--color-danger': '#dc2626',
			'--color-danger-hover': '#b91c1c',
			'--color-danger-active': '#991b1b',
			'--color-danger-ring': '#dc2626',
			'--color-success': '#16a34a',
			'--color-success-bg': '#f0fdf4',
			'--color-success-border': '#bbf7d0',
			'--color-warning': '#d97706',
			'--color-warning-bg': '#fffbeb',
			'--color-warning-border': '#fde68a',
			'--color-surface': '#f8fafc',
			'--color-surface-hover': '#f1f5f9',
			'--color-surface-active': '#e2e8f0',
			'--color-surface-border': '#cbd5e1',
			'--color-surface-border-hover': '#94a3b8',
			'--color-text': '#0f172a',
			'--color-text-muted': '#475569',
			'--color-text-subtle': '#94a3b8',
			'--color-text-inverted': '#ffffff',
			'--color-input-border': '#cbd5e1',
			'--color-input-border-hover': '#94a3b8',
			'--color-input-ring': '#1e293b',
			'--color-input-placeholder': '#94a3b8',
			'--color-input-disabled-bg': '#e2e8f0',
			'--color-input-disabled-text': '#94a3b8',
			'--color-input-error': '#dc2626',
			'--color-input-error-ring': '#dc2626',
		},
		dark: {
			'--color-brand': '#f1f5f9',
			'--color-brand-hover': '#e2e8f0',
			'--color-brand-active': '#cbd5e1',
			'--color-brand-ring': '#f1f5f9',
			'--color-brand-fg': '#0f172a',
			'--color-danger': '#f87171',
			'--color-danger-hover': '#fca5a5',
			'--color-danger-active': '#fecaca',
			'--color-danger-ring': '#f87171',
			'--color-success': '#4ade80',
			'--color-success-bg': '#052e16',
			'--color-success-border': '#166534',
			'--color-warning': '#fbbf24',
			'--color-warning-bg': '#1c1200',
			'--color-warning-border': '#92400e',
			'--color-surface': '#020617',
			'--color-surface-hover': '#0f172a',
			'--color-surface-active': '#1e293b',
			'--color-surface-border': '#1e293b',
			'--color-surface-border-hover': '#334155',
			'--color-text': '#f1f5f9',
			'--color-text-muted': '#94a3b8',
			'--color-text-subtle': '#1e293b',
			'--color-text-inverted': '#020617',
			'--color-input-border': '#1e293b',
			'--color-input-border-hover': '#334155',
			'--color-input-ring': '#f1f5f9',
			'--color-input-placeholder': '#334155',
			'--color-input-disabled-bg': '#0f172a',
			'--color-input-disabled-text': '#1e293b',
			'--color-input-error': '#f87171',
			'--color-input-error-ring': '#f87171',
		},
	},
	plum: {
		light: {
			'--color-brand': '#7c3aed',
			'--color-brand-hover': '#6d28d9',
			'--color-brand-active': '#5b21b6',
			'--color-brand-ring': '#7c3aed',
			'--color-brand-fg': '#ffffff',
			'--color-danger': '#dc2626',
			'--color-danger-hover': '#b91c1c',
			'--color-danger-active': '#991b1b',
			'--color-danger-ring': '#dc2626',
			'--color-success': '#16a34a',
			'--color-success-bg': '#f0fdf4',
			'--color-success-border': '#bbf7d0',
			'--color-warning': '#d97706',
			'--color-warning-bg': '#fffbeb',
			'--color-warning-border': '#fde68a',
			'--color-surface': '#ffffff',
			'--color-surface-hover': '#f5f3ff',
			'--color-surface-active': '#ede9fe',
			'--color-surface-border': '#ddd6fe',
			'--color-surface-border-hover': '#c4b5fd',
			'--color-text': '#2e1065',
			'--color-text-muted': '#5b21b6',
			'--color-text-subtle': '#c4b5fd',
			'--color-text-inverted': '#ffffff',
			'--color-input-border': '#ddd6fe',
			'--color-input-border-hover': '#c4b5fd',
			'--color-input-ring': '#7c3aed',
			'--color-input-placeholder': '#c4b5fd',
			'--color-input-disabled-bg': '#ede9fe',
			'--color-input-disabled-text': '#c4b5fd',
			'--color-input-error': '#dc2626',
			'--color-input-error-ring': '#dc2626',
		},
		dark: {
			'--color-brand': '#a78bfa',
			'--color-brand-hover': '#c4b5fd',
			'--color-brand-active': '#ddd6fe',
			'--color-brand-ring': '#a78bfa',
			'--color-brand-fg': '#2e1065',
			'--color-danger': '#f87171',
			'--color-danger-hover': '#fca5a5',
			'--color-danger-active': '#fecaca',
			'--color-danger-ring': '#f87171',
			'--color-success': '#4ade80',
			'--color-success-bg': '#052e16',
			'--color-success-border': '#166534',
			'--color-warning': '#fbbf24',
			'--color-warning-bg': '#1c1200',
			'--color-warning-border': '#92400e',
			'--color-surface': '#080412',
			'--color-surface-hover': '#0f0920',
			'--color-surface-active': '#190e30',
			'--color-surface-border': '#251546',
			'--color-surface-border-hover': '#321e5e',
			'--color-text': '#ede9fe',
			'--color-text-muted': '#a78bfa',
			'--color-text-subtle': '#251546',
			'--color-text-inverted': '#080412',
			'--color-input-border': '#251546',
			'--color-input-border-hover': '#321e5e',
			'--color-input-ring': '#a78bfa',
			'--color-input-placeholder': '#251546',
			'--color-input-disabled-bg': '#0f0920',
			'--color-input-disabled-text': '#251546',
			'--color-input-error': '#f87171',
			'--color-input-error-ring': '#f87171',
		},
	},
};

function renderTokens(tokens: Record<string, string>, indent = '\t'): string
{
	return Object.entries(tokens)
		.map(([k, v]) => `${indent}${k}: ${v};`)
		.join('\n');
}

export function generateCss(config: DaFinkConfig): string
{
	const { style, palette } = config;
	const isDefaultCombo = style === 'minimal' && palette === 'zinc';

	if(isDefaultCombo)
		return '/* Generated by dafink-ui — re-run `npx dafink-ui init` to update */\n';

	const styleLabel = style.charAt(0).toUpperCase() + style.slice(1);
	const paletteLabel = palette.charAt(0).toUpperCase() + palette.slice(1);

	const rootSections: string[] = [];
	const darkSections: string[] = [];

	if(style !== 'minimal')
	{
		const lightStyle = STYLE_TOKENS[style].light;
		rootSections.push(`\t/* Style: ${styleLabel} */\n${renderTokens(lightStyle)}`);

		const darkStyle = STYLE_TOKENS[style].dark;
		if(Object.keys(darkStyle).length > 0)
			darkSections.push(`\t/* Style: ${styleLabel} (dark) */\n${renderTokens(darkStyle)}`);
	}

	const lightPalette = PALETTE_TOKENS[palette].light;
	rootSections.push(`\t/* Palette: ${paletteLabel} */\n${renderTokens(lightPalette)}`);

	const darkPalette = PALETTE_TOKENS[palette].dark;
	darkSections.push(`\t/* Palette: ${paletteLabel} (dark) */\n${renderTokens(darkPalette)}`);

	const rootBlock = `:root {\n${rootSections.join('\n\n')}\n}`;
	const darkBlock = `.dark {\n${darkSections.join('\n\n')}\n}`;

	return `/* Generated by dafink-ui — re-run \`npx dafink-ui init\` to update */\n\n${rootBlock}\n\n${darkBlock}\n`;
}
